### ISSUE TITLE
Unable to install package without previously installed requests package

### ISSUE THREAD

**Issue by homier** [philippbosch/slack-webhook-cli#2]
Getting the package version from slack.py triggers requests import.

```
pip install slack-webhook-cli
Collecting slack-webhook-cli
  Using cached slack-webhook-cli-0.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kayig7mf/slack-webhook-cli/setup.py", line 3, in <module>
        version = __import__('slack').get_version()
      File "/tmp/pip-build-kayig7mf/slack-webhook-cli/slack.py", line 8, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
```

**Comment by philippbosch** [comment]
Oh, yeah. Never noticed because I have requests installed globally. I just pushed 0.2.4 that fixes this.
